# Generated by Django 6.0.3 on 2026-04-07 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('romantic', 'Romantic'), ('dance', 'Dance / Party'), ('sad', 'Sad / Emotional'), ('item', 'Item Song'), ('qawwali', 'Qawwali'), ('ghazal', 'Ghazal'), ('classical', 'Classical'), ('folk', 'Folk'), ('patriotic', 'Patriotic'), ('devotional', 'Devotional'), ('rap', 'Rap / Hip-Hop'), ('remix', 'Remix'), ('sufi', 'Sufi'), ('indie', 'Indie / Non-Film')], default='romantic', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20),
        ),
        migrations.CreateModel(
            name='LabelSong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('movie', models.CharField(blank=True, max_length=200)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('original_language', models.CharField(default='English', max_length=50)),
                ('official_lyrics', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('label_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='label_songs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
