# Generated by Django 6.0.3 on 2026-04-07 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_genre_alter_song_status_labelsong'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genre',
            old_name='genre',
            new_name='name',
        ),
    ]
