# Generated by Django 6.0.3 on 2026-04-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelsong',
            name='genre',
            field=models.CharField(blank=True, choices=[('romantic', 'Romantic'), ('dance', 'Dance / Party'), ('sad', 'Sad / Emotional'), ('item', 'Item Song'), ('qawwali', 'Qawwali'), ('ghazal', 'Ghazal'), ('classical', 'Classical'), ('folk', 'Folk'), ('patriotic', 'Patriotic'), ('devotional', 'Devotional'), ('rap', 'Rap / Hip-Hop'), ('remix', 'Remix'), ('sufi', 'Sufi'), ('indie', 'Indie / Non-Film')], max_length=50),
        ),
    ]
