# Generated by Django 6.0.3 on 2026-04-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_labelsong_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('verifier', 'Label')], default='user', max_length=20),
        ),
    ]
