# Generated by Django 6.0.3 on 2026-04-07 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_labelsong_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labelsong',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('bn', 'Bengali')], default='English', max_length=50),
        ),
    ]
