# Generated by Django 6.0.3 on 2026-04-08 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_labelsong_original_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='song',
            name='movie',
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('bn', 'Bengali')], max_length=10)),
            ],
            options={
                'unique_together': {('text', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translated_text', models.CharField(max_length=255)),
                ('target_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('bn', 'Bengali')], max_length=10)),
                ('source_word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='api.word')),
            ],
            options={
                'unique_together': {('source_word', 'target_language')},
            },
        ),
    ]
