# Generated by Django 6.0.3 on 2026-04-08 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_song_artist_remove_song_movie_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='rating',
            field=models.FloatField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
