# Generated by Django 6.0.3 on 2026-04-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_song_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, choices=[('romantic', 'Romantic'), ('dance', 'Dance / Party'), ('sad', 'Sad / Emotional'), ('item', 'Item Song'), ('qawwali', 'Qawwali'), ('ghazal', 'Ghazal'), ('classical', 'Classical'), ('folk', 'Folk'), ('patriotic', 'Patriotic'), ('devotional', 'Devotional'), ('rap', 'Rap / Hip-Hop'), ('remix', 'Remix'), ('sufi', 'Sufi'), ('indie', 'Indie / Non-Film')], max_length=15),
        ),
        migrations.AlterField(
            model_name='song',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('mr', 'Marathi'), ('ta', 'Tamil'), ('bn', 'Bengali')], default='English', max_length=50),
        ),
    ]
