# Generated by Django 6.0.3 on 2026-04-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_annotationrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('partially_accepted', 'Partially Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
